[package]
name = "shared_library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.192"
log = "0.4.20"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
rayon = "1.8.0"