[package]
name = "robotdreams"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io = "0.0.2"
slug = "0.1.4"
csv = "1.1"
flume = "0.11.0"
